apiVersion: apps/v1
kind: Deployment
metadata:
  name: labsapp-k8
  labels:
    app: labsapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: labsapp
  template:
    metadata:
      labels:
        app: labsapp
    spec:
      containers:
        - name: spring-boot-k8s
          image: rishabhm148/labs-app:v4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/masterDB
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123456789" # Password value wrapped in quotes
---
apiVersion: v1
kind: Service
metadata:
  name: labsapp-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
  selector:
    app: labsapp
